### ISSUE TITLE
loading into a custom menu tab in the admin

### ISSUE THREAD

**Issue by MrHDOLEK** [BenBroide/create-react-app-wp-admin#3]
I used your loader to create the plugin view in wordpress.And I have a problem because it generates a new tab in the admin menu and after entering it renders a div as injected from a react built in this particular div.

Example:

```php
add_action('admin_menu','init_plugins');
  function init_plugins()
  {
      add_menu_page('Forms','Test','manage_options','test','render','dashicons-admin-page',999);
  }
 function render()
    {
        ?>
        <div id="root">
           
        </div>
        <?php
    }
```

**Comment by BenBroide** [comment]
Can you share more details want in the issue?
Does the react app load?
What is the issue?
Add screenshots of the issue if possible

**Comment by MrHDOLEK** [comment]
problem is that I can't load react to the div which is rendered in the plugin tab

**Comment by BenBroide** [comment]
You need to adjust the value of 	private $limit_load_hook = ''; to the page you created. Currently it’s set for the main admin page

**Comment by MrHDOLEK** [comment]
Thanks for the answers, but could you give an example because I don't fully understand.
